# Generated by Django 5.1.4 on 2024-12-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(max_length=512)),
                ('album_name', models.CharField(max_length=512)),
                ('album_image', models.CharField(max_length=512)),
                ('album_url', models.CharField(max_length=512)),
                ('album_release_date', models.CharField(max_length=512)),
                ('album_type', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.CharField(max_length=512)),
                ('artist_name', models.CharField(max_length=512)),
                ('artist_url', models.CharField(max_length=512)),
            ],
        ),
    ]
